### ISSUE TITLE
add python: 2.7 to yml

### ISSUE THREAD

**Issue by jebyrnes** [yihui/travis-exitwp#61]
FYI, the default version of python has changed and will not build correctly unless you specify the version to 2.7.

**Comment by yihui** [comment]
@benrwoodard tried to do it but didn't really submit a PR: https://github.com/yihui/travis-exitwp/commit/6d9bd51ce2238259d63d45044305ffd2f5eee78b I'll do it myself. Thanks for the reminder again!
