### ISSUE TITLE
Switch to GHA

### ISSUE THREAD

**Issue by cderv** [yihui/travis-exitwp#74]

**Comment by cderv** [comment]
@yihui can you assign me on this, and/or maybe give me more access ? 

Otherwise, I'll work on a fort.

**Comment by cderv** [comment]
FWIW there is a port to switch directly to Hugo it seems: https://github.com/wooni005/exitwp-for-hugo

It is quite old though so it should not be new to you. And it also mean it probably runs with python 2.7 and not python 3 - the former being EOL now I think.

**Comment by yihui** [comment]
Done now.

**Comment by cderv** [comment]
Well done !
